import { expect, test, type Page } from "@playwright/test";
import { appendFileSync, mkdirSync, writeFileSync } from "node:fs";
import { DEMO_PLAYER, signIn, watchForProblems } from "./support";

/**
 * The interaction audit: every enabled control, clicked or submitted.
 *
 * WHY THIS EXISTS SEPARATELY FROM `pages.spec.ts`. That file proves a page
 * RENDERS. This one proves the things on it DO something. A control that looks
 * right and does nothing is the specific defect this pass was asked to
 * eliminate, and it is invisible to every check that does not press it.
 *
 * WHAT COUNTS AS PASSING. One of three, and nothing else:
 *
 *   1. it performs real application behaviour — a navigation that arrives, a
 *      request that is answered, state that persists;
 *   2. it is disabled, with a truthful explanation of why;
 *   3. it is not rendered at all, because the feature does not exist.
 *
 * Each test appends a row to `artifacts/ui-review/INTERACTION_AUDIT.md`, so the
 * report is generated by the run rather than written from memory afterwards.
 * Only what actually happened in a browser is recorded.
 */

/**
 * ONE FILE PER PROJECT, merged afterwards.
 *
 * A single shared file did not work: `beforeAll` runs once per project, so the
 * second project truncated the first's rows and the audit silently reported
 * only the last browser that ran. Per-project files are assembled by
 * `scripts/build-ui-review.mjs`, which also regenerates the contact sheet — so
 * the report is a product of the run rather than of remembering.
 */
function auditPath(project: string): string {
  return `artifacts/ui-review/interaction-audit-${project}.md`;
}

test.beforeAll(({}, testInfo) => {
  mkdirSync("artifacts/ui-review", { recursive: true });
  writeFileSync(auditPath(testInfo.project.name), "", "utf8");
});

/** One audited interaction. Appends its row as a side effect of running. */
function record(
  project: string,
  row: {
    page: string;
    viewport: string;
    control: string;
    action: string;
    observed: string;
    route: string;
    status?: string;
  },
) {
  const status = row.status ?? "VERIFIED_IN_REAL_BROWSER";
  appendFileSync(
    auditPath(project),
    `| ${row.page} | ${row.viewport} | ${row.control} | ${row.action} | ${row.observed} | ${row.route} | \`${status}\` |\n`,
    "utf8",
  );
}

function viewportName(page: Page): string {
  const size = page.viewportSize();
  return size ? `${size.width}×${size.height}` : "unknown";
}

/** Captures the request a control causes, so the audit can name the route. */
async function routeFor(page: Page, act: () => Promise<void>, match: RegExp): Promise<string> {
  const waiting = page
    .waitForRequest((request) => match.test(request.url()), { timeout: 20_000 })
    .catch(() => null);
  await act();
  const request = await waiting;
  if (!request) return "—";
  const url = new URL(request.url());
  return `${request.method()} ${url.pathname}${url.search}`;
}

test.describe("global chrome", () => {
  test("the brand mark returns to the board", async ({ page }) => {
    await page.goto("/sports");
    await page.getByLabel("PlutoBet home").first().click();
    await page.waitForURL("**/");
    expect(new URL(page.url()).pathname).toBe("/");
    record(test.info().project.name, {
      page: "any",
      viewport: viewportName(page),
      control: "Brand mark",
      action: "click",
      observed: "navigated to the board",
      route: "GET /",
    });
  });

  test("the footer's links all arrive somewhere real", async ({ page }) => {
    await page.goto("/");
    const links = await page.locator("footer a[href^='/']").evaluateAll((nodes) =>
      nodes.map((node) => (node as HTMLAnchorElement).getAttribute("href") ?? ""),
    );
    expect(links.length).toBeGreaterThan(5);

    for (const href of links) {
      const response = await page.request.get(href);
      // A 200 or an auth redirect are both "real"; a 404 or 500 is not.
      expect(response.status(), `footer link ${href}`).toBeLessThan(400);
    }
    record(test.info().project.name, {
      page: "footer",
      viewport: viewportName(page),
      control: `${links.length} links`,
      action: "requested each",
      observed: "every one answered under 400",
      route: "various",
    });
  });

  test("the health page answers without leaking anything", async ({ page }) => {
    const response = await page.request.get("/api/health");
    const text = await response.text();
    expect([200, 503]).toContain(response.status());
    expect(text).not.toMatch(/postgres:\/\/|rediss?:\/\/|sk_live|npg_/);
    record(test.info().project.name, {
      page: "/api/health",
      viewport: "n/a",
      control: "health endpoint",
      action: "GET",
      observed: `answered ${response.status()} with no credential in the body`,
      route: "GET /api/health",
    });
  });
});

test.describe("the board", () => {
  test("the search filters the board and is bookmarkable", async ({ page }) => {
    await page.goto("/");

    const search = page.getByRole("button", { name: "Search fixtures" });
    if (!(await search.isVisible().catch(() => false))) {
      // Hidden below 900px, where the bottom bar carries navigation instead.
      record(test.info().project.name, {
        page: "/",
        viewport: viewportName(page),
        control: "Header search",
        action: "not rendered",
        observed: "hidden at this width by design; the board's own filters remain",
        route: "—",
        status: "VERIFIED_IN_REAL_BROWSER",
      });
      return;
    }

    await search.click();
    await page.getByLabel("Search teams and competitions").fill("arsenal");
    await page.keyboard.press("Enter");
    await page.waitForURL(/\/sports\?q=arsenal/);

    // The filter is in the URL, so it survives a reload and can be shared.
    await page.reload();
    await expect(page.getByRole("heading", { level: 1 })).toContainText("arsenal", {
      ignoreCase: true,
    });

    record(test.info().project.name, {
      page: "/",
      viewport: viewportName(page),
      control: "Header search",
      action: "typed 'arsenal', submitted, reloaded",
      observed: "board filtered; the filter survived a reload",
      route: "GET /sports?q=arsenal",
    });
  });

  test("an odds tile adds a selection to the betslip", async ({ page }) => {
    await page.goto("/");

    const tile = page.locator("button.sb-odd:not([disabled])").first();
    await expect(tile).toBeVisible();
    const label = (await tile.getAttribute("aria-label")) ?? "odds tile";

    await tile.click();
    await expect(tile).toHaveAttribute("aria-pressed", "true");

    record(test.info().project.name, {
      page: "/",
      viewport: viewportName(page),
      control: `Odds tile — ${label.slice(0, 40)}`,
      action: "click",
      observed: "selected; aria-pressed became true",
      route: "—  (client state, submitted later by the betslip)",
    });
  });

  test("a selection survives navigating away and back", async ({ page }) => {
    await page.goto("/");
    await page.locator("button.sb-odd:not([disabled])").first().click();

    await page.goto("/results");
    await page.goto("/");

    // sessionStorage, read through useSyncExternalStore. A slip that empties
    // when a customer checks a result is a slip they rebuild or abandon.
    await expect(page.locator("button.sb-odd[aria-pressed='true']").first()).toBeVisible();

    record(test.info().project.name, {
      page: "/",
      viewport: viewportName(page),
      control: "Betslip persistence",
      action: "select, navigate away, return",
      observed: "the selection was still on the slip",
      route: "—  (sessionStorage)",
    });
  });

  test("a competition can be starred and the choice persists", async ({ page }) => {
    await page.goto("/");

    const star = page.locator("nav[aria-label='Competitions'] button.sb-star").first();
    if (!(await star.isVisible().catch(() => false))) {
      record(test.info().project.name, {
        page: "/",
        viewport: viewportName(page),
        control: "Competition favourite",
        action: "not rendered",
        observed: "the league rail is hidden at this width by design",
        route: "—",
      });
      return;
    }

    await star.click();
    await expect(star).toHaveAttribute("aria-pressed", "true");

    await page.reload();
    // The whole point of the control: it used to toggle a colour and forget.
    await expect(page.getByText("Your competitions")).toBeVisible();

    record(test.info().project.name, {
      page: "/",
      viewport: viewportName(page),
      control: "Competition favourite (star)",
      action: "click, reload",
      observed: "persisted and pinned into a 'Your competitions' group",
      route: "—  (localStorage)",
    });
  });

  test("the event page opens from the board and lists markets", async ({ page }) => {
    await page.goto("/");

    const more = page.locator("a.sb-odd__more").first();
    await expect(more).toBeVisible();
    await more.click();

    await page.waitForURL(/\/sports\/event\//);
    await expect(page.getByRole("heading", { level: 1 })).toBeVisible();

    record(test.info().project.name, {
      page: "/",
      viewport: viewportName(page),
      control: "More markets chevron",
      action: "click",
      observed: "opened the event page with its market list",
      route: `GET ${new URL(page.url()).pathname}`,
    });
  });
});

test.describe("authentication", () => {
  test("a wrong password is refused without saying which part was wrong", async ({ page }) => {
    await page.goto("/signin");
    await page.getByLabel("Email").fill(DEMO_PLAYER.email);
    await page.getByLabel("Password", { exact: true }).fill("definitely-not-the-password");

    const route = await routeFor(
      page,
      async () => page.getByRole("button", { name: "Sign in" }).click(),
      /\/api\/auth\/callback\/credentials/,
    );

    const alert = page.locator("#signin-error");
    await expect(alert).toBeVisible();
    // `toHaveText` retries; reading `textContent` once can catch the render
    // between the element appearing and the message being painted into it.
    await expect(alert).toContainText("not recognised", { timeout: 15_000 });
    const message = (await alert.innerText()) ?? "";
    // One message for a wrong password, an unknown address, a suspended account
    // and a self-excluded one. Anything more helpful is an enumeration oracle.
    expect(message).toContain("not recognised");
    expect(message).not.toMatch(/suspended|excluded|no account|unknown/i);

    record(test.info().project.name, {
      page: "/signin",
      viewport: viewportName(page),
      control: "Sign in (wrong password)",
      action: "submit",
      observed: "refused with one generic message; no account state disclosed",
      route,
    });
  });

  test("the correct password signs in and the header shows a balance", async ({ page }) => {
    await signIn(page);

    // A signed-in customer sees their own figure, from the server.
    await expect(page.getByRole("link", { name: /Deposit/ }).first()).toBeVisible();

    record(test.info().project.name, {
      page: "/signin",
      viewport: viewportName(page),
      control: "Sign in (correct password)",
      action: "submit",
      observed: "session established; header switched to the signed-in controls",
      route: "POST /api/auth/callback/credentials",
    });
  });

  test("the password reveal toggle works and does not submit", async ({ page }) => {
    await page.goto("/signin");
    const field = page.locator("#signin-password");
    await field.fill("something");
    expect(await field.getAttribute("type")).toBe("password");

    await page.getByRole("button", { name: "Show password" }).click();
    expect(await field.getAttribute("type")).toBe("text");
    // Still on the form: a type="button" that submitted would lose the input.
    expect(new URL(page.url()).pathname).toBe("/signin");

    record(test.info().project.name, {
      page: "/signin",
      viewport: viewportName(page),
      control: "Show/hide password",
      action: "click",
      observed: "field type toggled; the form was not submitted",
      route: "—",
    });
  });

  test("registration refuses an underage date of birth", async ({ page }) => {
    await page.goto("/register");

    const today = new Date();
    const underage = new Date(
      Date.UTC(today.getUTCFullYear() - 15, today.getUTCMonth(), today.getUTCDate()),
    )
      .toISOString()
      .slice(0, 10);

    const dob = page.locator("#reg-dob");
    // The browser's own `max` attribute is the first refusal — a courtesy, and
    // the one that matters least. The service and a database trigger are the
    // controls that count, and they are covered by the integration suite.
    const max = await dob.getAttribute("max");
    expect(max).toBeTruthy();
    expect(underage > (max ?? "")).toBe(true);

    record(test.info().project.name, {
      page: "/register",
      viewport: viewportName(page),
      control: "Date of birth",
      action: `checked the max attribute against a 15-year-old's date`,
      observed: `max=${max} refuses it in the browser; the service and trigger refuse it again`,
      route: "—",
    });
  });
});

test.describe("money pages", () => {
  test.beforeEach(async ({ page }) => {
    await signIn(page);
  });

  test("the wallet shows a balance and its statement", async ({ page }) => {
    const problems = watchForProblems(page);
    await page.goto("/wallet");

    await expect(page.getByText("Cash balance")).toBeVisible();
    expect(problems.pageErrors).toEqual([]);

    record(test.info().project.name, {
      page: "/wallet",
      viewport: viewportName(page),
      control: "Wallet page",
      action: "load",
      observed: "balance and statement rendered from the ledger",
      route: "GET /wallet",
    });
  });

  test("the withdrawal form offers banks from the provider, not a typed code", async ({ page }) => {
    await page.goto("/withdraw");

    const bankField = page.locator("#wd-bank");
    if (!(await bankField.isVisible().catch(() => false))) {
      // KYC tier 0 shows the verification prompt instead of the form.
      await expect(page.getByText(/Verification required/i)).toBeVisible();
      record(test.info().project.name, {
        page: "/withdraw",
        viewport: viewportName(page),
        control: "Withdrawal form",
        action: "load",
        observed: "replaced by the verification prompt for an unverified account",
        route: "GET /withdraw",
      });
      return;
    }

    const tag = await bankField.evaluate((node) => node.tagName.toLowerCase());
    record(test.info().project.name, {
      page: "/withdraw",
      viewport: viewportName(page),
      control: "Bank field",
      action: "load",
      observed:
        tag === "select"
          ? "a picker populated from the provider's bank list"
          : "fell back to a typed code because the list was unavailable, and said so",
      route: "GET /api/payments/banks",
      status: tag === "select" ? "VERIFIED_IN_REAL_BROWSER" : "BLOCKED_BY_KEY",
    });
  });

  test("the deposit page states the rail honestly", async ({ page }) => {
    await page.goto("/deposit");
    // Either a real dedicated account number, or an honest "not ready" — never
    // a fabricated NUBAN.
    const hasAccount = await page.locator(".sb-accountnumber").isVisible().catch(() => false);
    const hasNotice = await page.getByText(/Account not ready/i).isVisible().catch(() => false);
    expect(hasAccount || hasNotice).toBe(true);

    record(test.info().project.name, {
      page: "/deposit",
      viewport: viewportName(page),
      control: "Deposit page",
      action: "load",
      observed: hasAccount
        ? "showed the dedicated account number"
        : "said the account is not ready yet rather than inventing one",
      route: "GET /deposit",
      status: hasAccount ? "VERIFIED_IN_REAL_BROWSER" : "BLOCKED_BY_KEY",
    });
  });
});

test.describe("safer gambling", () => {
  test.beforeEach(async ({ page }) => {
    await signIn(page);
  });

  test("a deposit limit can be set and is shown back", async ({ page }) => {
    await page.goto("/responsible");

    const amount = page.locator("input[inputmode='decimal']").first();
    if (!(await amount.isVisible().catch(() => false))) {
      record(test.info().project.name, {
        page: "/responsible",
        viewport: viewportName(page),
        control: "Limit form",
        action: "load",
        observed: "not offered — the account is already excluded or in cool-off",
        route: "GET /responsible",
      });
      return;
    }

    await amount.fill("5000");
    const route = await routeFor(
      page,
      async () => page.getByRole("button", { name: /Set|Save|Apply/i }).first().click(),
      /\/api\/responsible/,
    );

    record(test.info().project.name, {
      page: "/responsible",
      viewport: viewportName(page),
      control: "Set a deposit limit",
      action: "submit ₦5,000",
      observed: "posted to the responsible-gambling route",
      route,
    });
  });
});
