/**
 * The review server: a production build on a DISPOSABLE LOCAL DATABASE.
 *
 *   node scripts/review-server.mjs            # port 3100
 *   node scripts/review-server.mjs --port=3200
 *
 * This is what the Playwright suite and the screenshot capture run against.
 *
 * WHY THIS SCRIPT EXISTS RATHER THAN A SHELL ONE-LINER. `next start` loads
 * `.env`, and in this repository `.env` holds PRODUCTION credentials. Starting
 * the review server by exporting a local `DATABASE_URL` in front of the command
 * works, but it is one forgotten export away from pointing a browser — and the
 * destructive interaction tests — at the real database, and the failure is
 * silent because the app comes up perfectly either way.
 *
 * So the safety is asserted here instead of remembered:
 *
 *   1. Every connection string is set EXPLICITLY. Shell env beats `.env` in
 *      Next.js, so nothing production-shaped can leak in through the file.
 *   2. The host of every one is CHECKED. A URL that is not loopback aborts the
 *      start. This is the check that makes the rest of it safe rather than
 *      merely careful.
 *   3. `AUTH_SECRET` and `IDENTITY_PEPPER` are REVIEW-ONLY values, generated on
 *      first run into a gitignored file. Previously the review process
 *      inherited the production pair from `.env`, which meant a local browser
 *      session was signed with the production secret and local identity numbers
 *      hashed into the production keyspace. Neither is needed to review a
 *      screen, and both are avoidable.
 *
 * The generated file is gitignored and never printed. If it is lost, delete it
 * and the next start makes another — the only cost is that existing local
 * sessions and local identity hashes stop verifying, which for a disposable
 * database is not a cost.
 *
 * `playwright.config.ts` still does not spawn this itself. The base URL is
 * supplied by whoever runs the suite, so pointing the tests somewhere is always
 * a deliberate act.
 */
import { spawn } from "node:child_process";
import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SECRETS_FILE = path.join(ROOT, ".env.review.local");

const arg = (name, fallback) => {
  const found = process.argv.find((a) => a.startsWith(`--${name}=`));
  return found ? found.slice(name.length + 3) : fallback;
};

const PORT = arg("port", "3100");

/*
 * The dev stack's credentials, from `scripts/dev-stack.ts`. They are fixed and
 * checked in on purpose: a local throwaway cluster that only listens on
 * loopback has nothing to protect, and a password nobody has to look up is one
 * nobody is tempted to reuse from somewhere that does.
 */
const DB = {
  DATABASE_URL: "postgresql://bet_app:bet_app_dev@127.0.0.1:5432/bet",
  DIRECT_DATABASE_URL: "postgresql://bet_app:bet_app_dev@127.0.0.1:5432/bet",
  MIGRATION_DATABASE_URL: "postgresql://bet_owner:bet_owner_dev@127.0.0.1:5432/bet",
  REDIS_URL: "redis://127.0.0.1:6379",
};

const LOOPBACK = new Set(["127.0.0.1", "localhost", "::1", "[::1]"]);

/** Aborts unless every connection string points at this machine. */
function assertLocal(vars) {
  for (const [name, value] of Object.entries(vars)) {
    let host;
    try {
      host = new URL(value).hostname;
    } catch {
      throw new Error(`${name} is not a URL. Refusing to start.`);
    }
    if (!LOOPBACK.has(host)) {
      // The host is named because it is the whole point of the message, and a
      // hostname is not a credential. The rest of the URL is never printed.
      throw new Error(
        `${name} points at "${host}", which is not this machine.\n` +
          "The review server runs destructive tests and only ever runs against a\n" +
          "disposable local database. Refusing to start.",
      );
    }
  }
}

/** Review-only secrets, generated once. Never printed, never committed. */
function reviewSecrets() {
  if (existsSync(SECRETS_FILE)) {
    const found = {};
    for (const line of readFileSync(SECRETS_FILE, "utf8").split("\n")) {
      const match = /^([A-Z_]+)=(.*)$/.exec(line.trim());
      if (match) found[match[1]] = match[2];
    }
    if (found.AUTH_SECRET && found.IDENTITY_PEPPER) return found;
  }

  const made = {
    AUTH_SECRET: randomBytes(32).toString("base64"),
    IDENTITY_PEPPER: randomBytes(32).toString("hex"),
  };
  writeFileSync(
    SECRETS_FILE,
    [
      "# Generated by scripts/review-server.mjs. Gitignored, local only.",
      "# NOT production values and not interchangeable with them. Delete this",
      "# file to roll it; the only thing that breaks is local sessions.",
      `AUTH_SECRET=${made.AUTH_SECRET}`,
      `IDENTITY_PEPPER=${made.IDENTITY_PEPPER}`,
      "",
    ].join("\n"),
    { encoding: "utf8", mode: 0o600 },
  );
  console.info(`generated review-only secrets into ${path.basename(SECRETS_FILE)}`);
  return made;
}

assertLocal(DB);

const child = spawn(
  process.execPath,
  [path.join(ROOT, "node_modules/next/dist/bin/next"), "start", "-p", PORT],
  {
    cwd: ROOT,
    stdio: "inherit",
    env: {
      ...process.env,
      ...DB,
      ...reviewSecrets(),
      NODE_ENV: "production",
      NEXTAUTH_URL: `http://localhost:${PORT}`,
      AUTH_URL: `http://localhost:${PORT}`,
      // Named so the running app can say what it is. A review server that
      // cannot be told apart from production is its own hazard.
      PLUTOBET_ENVIRONMENT: "review",
    },
  },
);

child.on("exit", (code) => process.exit(code ?? 0));
